inherit_from: 
  - .rubocop_todo.yml
  - .rubocop_factory_bot.yml

require: 
  - rubocop-jekyll
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable

Metrics/BlockLength:
    Exclude:
      - spec/**/*
